// packages/vue/src/WaveCounter.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch, type Component } from 'vue'
import type { Analytics, AnalyticsWindow, WaveCounterTransport } from '@waves-counter/client'

import AnalyticsChart from './AnalyticsChart.vue'
import CoffeeIcon from './CoffeeIcon.vue'
import { useWaveCounter } from './useWaveCounter.js'

type WaveCounterTheme = 'auto' | 'light' | 'dark'

const props = withDefaults(
  defineProps<{
    counterKey: string
    endpoint: string
    theme?: WaveCounterTheme
    icon?: Component
    showStats?: boolean
    analyticsWindow?: AnalyticsWindow
    longPressMs?: number
    transport?: WaveCounterTransport
  }>(),
  {
    theme: 'auto',
    icon: () => CoffeeIcon,
    showStats: true,
    longPressMs: 550,
  },
)

const emit = defineEmits<{
  error: [error: Error]
}>()

const analyticsWindows: { label: string; window: AnalyticsWindow }[] = [
  { label: '7D', window: '7d' },
  { label: '1M', window: '1M' },
  { label: 'All', window: 'all' },
]

const root = ref<HTMLElement | null>(null)
const trigger = ref<HTMLButtonElement | null>(null)
const popover = ref<HTMLElement | null>(null)
const openSource = ref<'pointer' | 'keyboard'>('pointer')
const animateChart = ref(false)
const popoverStyle = ref<Record<string, string>>({})
const wave = useWaveCounter({
  counterKey: props.counterKey,
  endpoint: props.endpoint,
  showStats: props.showStats,
  ...(props.analyticsWindow ? { analyticsWindow: props.analyticsWindow } : {}),
  ...(props.transport ? { transport: props.transport } : {}),
})
let longPressTimer: ReturnType<typeof setTimeout> | undefined
let pointerStart: { x: number; y: number } | undefined
let capturedPointerId: number | undefined
let longPressActivated = false

const total = computed(() => wave.counter.value?.total)
const unavailable = computed(() => !wave.loading.value && wave.counter.value === null)
const title = computed(() => `${capitalize(props.counterKey)} statistics`)
const triggerLabel = computed(() => {
  const count = total.value === undefined ? 'unavailable' : `${total.value} total`
  const statsHint = wave.statsEnabled.value
    ? ' Right click, long press, or use the context menu key for statistics.'
    : ''
  return `Add one ${props.counterKey}. ${count}.${statsHint}`
})
const comparison = computed(() => comparisonText(wave.analytics.value, wave.analyticsWindow.value))
const dateRange = computed(() => rangeText(wave.analytics.value, wave.analyticsWindow.value))
const accessibleSummary = computed(() => summaryText(wave.analytics.value, wave.analyticsWindow.value))

watch(
  () => props.showStats,
  (enabled) => wave.enableStats(enabled),
)

onMounted(() => {
  document.addEventListener('pointerdown', handleOutsidePointer)
  window.addEventListener('resize', updatePopoverPosition)
  void wave.load().catch(emitError)
})

onBeforeUnmount(() => {
  cancelLongPress()
  document.removeEventListener('pointerdown', handleOutsidePointer)
  window.removeEventListener('resize', updatePopoverPosition)
})

async function increment(): Promise<void> {
  if (longPressActivated) {
    longPressActivated = false
    return
  }
  try {
    await wave.increment()
  } catch (error) {
    emitError(error)
  }
}

async function openStats(source: 'pointer' | 'keyboard'): Promise<void> {
  if (!wave.statsEnabled.value) return
  openSource.value = source
  animateChart.value = source === 'pointer'
  const opening = wave.openStats()
  await nextTick()
  updatePopoverPosition()
  try {
    await opening
    await nextTick()
    updatePopoverPosition()
  } catch {
    // Analytics errors stay inside the popover and retry in place.
  }
}

function handleContextMenu(event: MouseEvent): void {
  if (!wave.statsEnabled.value) return
  event.preventDefault()
  void openStats('pointer')
}

function handleTriggerKeydown(event: KeyboardEvent): void {
  if (event.key === 'Escape' && wave.statsOpen.value) {
    event.preventDefault()
    closeAndRestoreFocus()
    return
  }
  if (event.key === 'ContextMenu' || (event.key === 'F10' && event.shiftKey)) {
    if (!wave.statsEnabled.value) return
    event.preventDefault()
    void openStats('keyboard')
  }
}

function handlePopoverKeydown(event: KeyboardEvent): void {
  if (event.key !== 'Escape') return
  event.preventDefault()
  closeAndRestoreFocus()
}

function closeAndRestoreFocus(): void {
  wave.closeStats()
  animateChart.value = false
  trigger.value?.focus({ preventScroll: true })
}

function handleOutsidePointer(event: PointerEvent): void {
  if (!wave.statsOpen.value || root.value?.contains(event.target as Node)) return
  wave.closeStats()
  animateChart.value = false
}

function handlePointerDown(event: PointerEvent): void {
  if (event.pointerType !== 'touch' || !wave.statsEnabled.value) return
  cancelLongPress()
  pointerStart = { x: event.clientX, y: event.clientY }
  capturedPointerId = event.pointerId
  event.currentTarget instanceof HTMLButtonElement &&
    event.currentTarget.setPointerCapture?.(event.pointerId)
  longPressActivated = false
  longPressTimer = setTimeout(() => {
    longPressActivated = true
    void openStats('pointer')
  }, props.longPressMs)
}

function handlePointerMove(event: PointerEvent): void {
  if (!pointerStart || event.pointerType !== 'touch') return
  const distance = Math.hypot(event.clientX - pointerStart.x, event.clientY - pointerStart.y)
  if (distance > 10) cancelLongPress()
}

function cancelLongPress(): void {
  if (longPressTimer !== undefined) clearTimeout(longPressTimer)
  longPressTimer = undefined
  pointerStart = undefined
  if (capturedPointerId !== undefined) {
    try {
      trigger.value?.releasePointerCapture?.(capturedPointerId)
    } catch {
      // Capture may already have ended after pointerup or pointercancel.
    }
  }
  capturedPointerId = undefined
}

function updatePopoverPosition(): void {
  if (!wave.statsOpen.value || !trigger.value || !popover.value) return
  const triggerRect = trigger.value.getBoundingClientRect()
  const rootFontSize = Number.parseFloat(getComputedStyle(document.documentElement).fontSize) || 16
  const gutter = rootFontSize
  const measuredWidth = popover.value.getBoundingClientRect().width
  const width =
    measuredWidth > 0
      ? measuredWidth
      : Math.min(20 * rootFontSize, Math.max(0, window.innerWidth - gutter * 2))
  const centeredLeft = triggerRect.left + triggerRect.width / 2 - width / 2
  const clampedLeft = Math.min(
    Math.max(gutter, centeredLeft),
    Math.max(gutter, window.innerWidth - width - gutter),
  )
  popoverStyle.value = {
    '--wave-popover-offset-x': `${clampedLeft - centeredLeft}px`,
  }
}

function emitError(error: unknown): void {
  emit('error', error instanceof Error ? error : new Error(String(error)))
}

async function retryAnalytics(): Promise<void> {
  try {
    await wave.loadAnalytics()
  } catch {
    // The renewed error remains visible in the popover.
  }
}

async function selectAnalyticsWindow(window: AnalyticsWindow): Promise<void> {
  try {
    await wave.setAnalyticsWindow(window)
    await nextTick()
    updatePopoverPosition()
  } catch {
    // The renewed error remains visible in the popover.
  }
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1)
}

function comparisonText(analytics: Analytics | null, window: AnalyticsWindow): string {
  if (!analytics) return ''
  if (window === 'all') {
    return analytics.total === 0 ? 'No all-time events' : `${analytics.total} all-time events`
  }
  const previousPeriod = window === '1M' ? 'previous 30 days' : 'previous seven days'
  if (analytics.previousTotal === 0) {
    return analytics.total === 0
      ? `No events in this or the ${previousPeriod}`
      : `${analytics.total} events, with none in the ${previousPeriod}`
  }
  const change = analytics.changePercentage ?? 0
  const direction = change >= 0 ? 'more' : 'less'
  return `${Math.abs(change)}% ${direction} than the ${previousPeriod}`
}

function rangeText(analytics: Analytics | null, window: AnalyticsWindow): string {
  if (!analytics?.points.length) return defaultRangeText(window)
  const formatter = new Intl.DateTimeFormat(undefined, {
    month: 'short',
    day: 'numeric',
    timeZone: 'UTC',
  })
  const first = analytics.points[0]
  const last = analytics.points.at(-1)
  return first && last
    ? `${formatter.format(new Date(first.start))} to ${formatter.format(new Date(last.start))}, UTC`
    : defaultRangeText(window)
}

function summaryText(analytics: Analytics | null, window: AnalyticsWindow): string {
  if (!analytics) return ''
  const dailyCounts = analytics.points.map((point) => point.count).join(', ')
  return `${analytics.total} events in ${windowSummary(window)}. Daily counts: ${dailyCounts}. ${comparisonText(analytics, window)}.`
}

function defaultRangeText(window: AnalyticsWindow): string {
  if (window === '1M') return 'Last 30 UTC days'
  if (window === 'all') return 'All-time UTC activity'
  return 'Last seven UTC days'
}

function windowSummary(window: AnalyticsWindow): string {
  if (window === '1M') return 'the last 30 days'
  if (window === 'all') return 'all time'
  return 'the last seven days'
}
</script>

<template>
  <span
    ref="root"
    class="wave-counter"
    :data-open-source="openSource"
    :data-stats-open="wave.statsOpen.value || undefined"
    :data-theme="theme"
  >
    <button
      ref="trigger"
      class="wave-counter__trigger"
      type="button"
      :aria-label="triggerLabel"
      :aria-haspopup="wave.statsEnabled.value ? 'dialog' : undefined"
      :aria-expanded="wave.statsEnabled.value ? wave.statsOpen.value : undefined"
      :aria-controls="wave.statsOpen.value ? `${counterKey}-wave-stats` : undefined"
      :aria-busy="wave.pendingIncrements.value > 0 || undefined"
      @click="increment"
      @contextmenu="handleContextMenu"
      @keydown="handleTriggerKeydown"
      @pointerdown="handlePointerDown"
      @pointermove="handlePointerMove"
      @pointerup="cancelLongPress"
      @pointercancel="cancelLongPress"
    >
      <span class="wave-counter__icon" aria-hidden="true">
        <slot name="icon">
          <component :is="icon" :size="18" :stroke-width="1.8" />
        </slot>
      </span>
      <slot :total="total ?? 0" :pending="wave.pendingIncrements.value" :unavailable="unavailable">
        <span data-total class="wave-counter__total">{{ total ?? '—' }}</span>
      </slot>
      <span v-if="unavailable" class="wave-counter__sr-only" role="status">Counter unavailable</span>
    </button>

    <Transition name="wave-popover">
      <section
        v-if="wave.statsOpen.value"
        ref="popover"
        :id="`${counterKey}-wave-stats`"
        class="wave-counter__popover"
        :style="popoverStyle"
        role="dialog"
        :aria-label="title"
        tabindex="-1"
        @keydown="handlePopoverKeydown"
      >
        <slot
          name="analytics"
          :analytics="wave.analytics.value"
          :window="wave.analyticsWindow.value"
          :loading="wave.analyticsLoading.value"
          :error="wave.analyticsError.value"
          :set-window="selectAnalyticsWindow"
          :retry="retryAnalytics"
        >
          <div class="wave-counter__heading">
            <div>
              <p class="wave-counter__eyebrow">Activity</p>
              <h2>{{ capitalize(counterKey) }}</h2>
            </div>
            <div class="wave-counter__heading-actions">
              <div class="wave-counter__window-switch" aria-label="Activity range">
                <button
                  v-for="option in analyticsWindows"
                  :key="option.window"
                  type="button"
                  :aria-label="option.label"
                  :aria-pressed="wave.analyticsWindow.value === option.window"
                  @click="selectAnalyticsWindow(option.window)"
                >
                  {{ option.label }}
                </button>
              </div>
              <button class="wave-counter__close" type="button" aria-label="Close statistics" @click="closeAndRestoreFocus">
                <span aria-hidden="true">×</span>
              </button>
            </div>
          </div>

          <div v-if="wave.analyticsLoading.value" class="wave-counter__loading" role="status">
            Loading activity
          </div>
          <div v-else-if="wave.analyticsError.value" class="wave-counter__error" role="alert">
            <p>Activity is unavailable.</p>
            <button type="button" @click="retryAnalytics">Try again</button>
          </div>
          <div v-else-if="wave.analytics.value" class="wave-counter__analytics">
            <div class="wave-counter__summary-row">
              <strong>{{ wave.analytics.value.total }}</strong>
              <span>events</span>
            </div>
            <p data-comparison class="wave-counter__comparison">{{ comparison }}</p>
            <AnalyticsChart
              :analytics="wave.analytics.value"
              :animate="animateChart"
            />
            <p class="wave-counter__range">{{ dateRange }}</p>
            <p data-accessible-summary class="wave-counter__sr-only">
              {{ accessibleSummary }}
            </p>
          </div>
        </slot>
      </section>
    </Transition>
  </span>
</template>

// packages/react/src/WaveCounter.tsx
import {
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from 'react'
import type { Analytics, AnalyticsWindow, WaveCounterTransport } from '@waves-counter/client'

import { AnalyticsChart } from './AnalyticsChart.js'
import { CoffeeIcon } from './CoffeeIcon.js'
import { useWaveCounter } from './useWaveCounter.js'

export type WaveCounterTheme = 'auto' | 'light' | 'dark'

export interface WaveCounterProps {
  counterKey: string
  endpoint: string
  theme?: WaveCounterTheme
  icon?: ReactNode | (() => ReactNode)
  showStats?: boolean
  analyticsWindow?: AnalyticsWindow
  longPressMs?: number
  transport?: WaveCounterTransport
  onError?: (error: Error) => void
  children?: (state: { total: number; pending: number; unavailable: boolean }) => ReactNode
  renderIcon?: () => ReactNode
  renderAnalytics?: (state: AnalyticsRenderState) => ReactNode
}

interface AnalyticsRenderState {
  analytics: Analytics | null
  window: AnalyticsWindow
  loading: boolean
  error: Error | null
  setWindow: (window: AnalyticsWindow) => Promise<void>
  retry: () => Promise<void>
}

type OpenSource = 'pointer' | 'keyboard'

const POPOVER_EXIT_MS = 160
const ANALYTICS_WINDOWS: { label: string; window: AnalyticsWindow }[] = [
  { label: '7D', window: '7d' },
  { label: '1M', window: '1M' },
  { label: 'All', window: 'all' },
]

export function WaveCounter({
  counterKey,
  endpoint,
  theme = 'auto',
  icon,
  showStats = true,
  analyticsWindow,
  longPressMs = 550,
  transport,
  onError,
  children,
  renderIcon,
  renderAnalytics,
}: WaveCounterProps): React.JSX.Element {
  const root = useRef<HTMLSpanElement>(null)
  const trigger = useRef<HTMLButtonElement>(null)
  const popover = useRef<HTMLElement>(null)
  const longPressTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined)
  const pointerOrigin = useRef<{ x: number; y: number } | undefined>(undefined)
  const capturedPointerId = useRef<number | undefined>(undefined)
  const longPressActivated = useRef(false)
  const enterFrame = useRef<number | undefined>(undefined)

  const [openSource, setOpenSource] = useState<OpenSource>('pointer')
  const [animateChart, setAnimateChart] = useState(false)
  const [mounted, setMounted] = useState(false)
  const [entering, setEntering] = useState(false)
  const [leaving, setLeaving] = useState(false)
  const [popoverStyle, setPopoverStyle] = useState<CSSProperties>({})

  const wave = useWaveCounter({
    counterKey,
    endpoint,
    showStats,
    ...(analyticsWindow ? { analyticsWindow } : {}),
    ...(transport ? { transport } : {}),
  })
  const total = wave.counter?.total
  const unavailable = !wave.loading && wave.counter === null
  const title = `${capitalize(counterKey)} statistics`
  const triggerLabel = describeTrigger(counterKey, total, wave.statsEnabled)

  const reducedMotion = () => window.matchMedia?.('(prefers-reduced-motion: reduce)').matches ?? false

  const cancelLongPress = () => {
    if (longPressTimer.current) clearTimeout(longPressTimer.current)
    longPressTimer.current = undefined
    pointerOrigin.current = undefined

    if (capturedPointerId.current !== undefined) {
      try {
        trigger.current?.releasePointerCapture?.(capturedPointerId.current)
      } catch {}
    }
    capturedPointerId.current = undefined
  }

  const cancelEnterFrame = () => {
    if (enterFrame.current !== undefined) cancelAnimationFrame(enterFrame.current)
    enterFrame.current = undefined
  }

  const updatePosition = () => {
    if (!trigger.current || !popover.current || !wave.statsOpen) return

    const triggerRect = trigger.current.getBoundingClientRect()
    const rootFontSize = Number.parseFloat(getComputedStyle(document.documentElement).fontSize) || 16
    const gutter = rootFontSize
    const measuredWidth = popover.current.getBoundingClientRect().width
    const popoverWidth = measuredWidth > 0
      ? measuredWidth
      : Math.min(20 * rootFontSize, Math.max(0, window.innerWidth - gutter * 2))
    const centeredLeft = triggerRect.left + triggerRect.width / 2 - popoverWidth / 2
    const clampedLeft = Math.min(
      Math.max(gutter, centeredLeft),
      Math.max(gutter, window.innerWidth - popoverWidth - gutter),
    )

    setPopoverStyle({
      '--wave-popover-offset-x': `${clampedLeft - centeredLeft}px`,
    } as CSSProperties)
  }

  const dismiss = (restoreFocus = false) => {
    wave.closeStats()
    setAnimateChart(false)
    cancelEnterFrame()
    setEntering(false)

    if (reducedMotion() || openSource === 'keyboard') {
      setLeaving(false)
      setMounted(false)
    } else {
      setLeaving(true)
      window.setTimeout(() => {
        setLeaving(false)
        setMounted(false)
      }, POPOVER_EXIT_MS)
    }

    if (restoreFocus) trigger.current?.focus({ preventScroll: true })
  }

  const open = async (source: OpenSource) => {
    if (!wave.statsEnabled) return

    const shouldAnimate = source === 'pointer' && !reducedMotion()
    setOpenSource(source)
    setAnimateChart(source === 'pointer')
    setLeaving(false)
    setMounted(true)
    setEntering(shouldAnimate)
    cancelEnterFrame()
    if (shouldAnimate) {
      enterFrame.current = requestAnimationFrame(() => {
        enterFrame.current = undefined
        setEntering(false)
        updatePosition()
      })
    }

    const opening = wave.openStats()
    requestAnimationFrame(updatePosition)
    try {
      await opening
    } catch {
      // The popover renders its analytics error and retry affordance.
    } finally {
      requestAnimationFrame(updatePosition)
    }
  }

  useEffect(() => {
    void wave.load().catch((error: unknown) => onError?.(asError(error)))
  }, [counterKey, endpoint, transport])

  useEffect(() => {
    if (wave.statsEnabled) return
    cancelEnterFrame()
    setEntering(false)
    setLeaving(false)
    setMounted(false)
  }, [wave.statsEnabled])

  useEffect(() => {
    const onOutsidePointer = (event: PointerEvent) => {
      if (wave.statsOpen && !root.current?.contains(event.target as Node)) dismiss()
    }

    document.addEventListener('pointerdown', onOutsidePointer)
    window.addEventListener('resize', updatePosition)
    return () => {
      cancelLongPress()
      cancelEnterFrame()
      document.removeEventListener('pointerdown', onOutsidePointer)
      window.removeEventListener('resize', updatePosition)
    }
  }, [wave.statsOpen, openSource])

  useLayoutEffect(() => {
    if (mounted) updatePosition()
  }, [mounted, wave.statsOpen, wave.analyticsLoading])

  const retry = async () => {
    try {
      await wave.loadAnalytics()
    } catch {
      // The controller retains the analytics error for the retry UI.
    }
  }

  const selectAnalyticsWindow = async (window: AnalyticsWindow) => {
    try {
      await wave.setAnalyticsWindow(window)
    } catch {
      // The controller retains the analytics error for the retry UI.
    } finally {
      requestAnimationFrame(updatePosition)
    }
  }

  const increment = async () => {
    if (longPressActivated.current) {
      longPressActivated.current = false
      return
    }

    try {
      await wave.increment()
    } catch (error) {
      onError?.(asError(error))
    }
  }

  const beginLongPress = (event: React.PointerEvent<HTMLButtonElement>) => {
    if ((event.pointerType && event.pointerType !== 'touch') || !wave.statsEnabled) return

    cancelLongPress()
    pointerOrigin.current = { x: event.clientX, y: event.clientY }
    capturedPointerId.current = event.pointerId
    event.currentTarget.setPointerCapture?.(event.pointerId)
    longPressActivated.current = false
    longPressTimer.current = setTimeout(() => {
      longPressActivated.current = true
      void open('pointer')
    }, longPressMs)
  }

  const cancelMovedLongPress = (event: React.PointerEvent<HTMLButtonElement>) => {
    if (
      pointerOrigin.current
      && (!event.pointerType || event.pointerType === 'touch')
      && Math.hypot(event.clientX - pointerOrigin.current.x, event.clientY - pointerOrigin.current.y) > 10
    ) {
      cancelLongPress()
    }
  }

  const comparison = comparisonText(wave.analytics, wave.analyticsWindow)
  const dateRange = rangeText(wave.analytics, wave.analyticsWindow)
  const summary = summaryText(wave.analytics, wave.analyticsWindow)
  const showPopover = mounted || wave.statsOpen || leaving
  const popoverClasses = [
    'wave-counter__popover',
    leaving ? 'wave-popover-leave-active wave-popover-leave-to' : undefined,
    entering ? 'wave-popover-enter-active wave-popover-enter-from' : undefined,
    !entering && !leaving && openSource === 'pointer' ? 'wave-popover-enter-active' : undefined,
  ].filter(Boolean).join(' ')

  return (
    <span
      ref={root}
      className="wave-counter"
      data-open-source={openSource}
      data-stats-open={wave.statsOpen || undefined}
      data-theme={theme}
    >
      <button
        ref={trigger}
        className="wave-counter__trigger"
        type="button"
        aria-label={triggerLabel}
        aria-haspopup={wave.statsEnabled ? 'dialog' : undefined}
        aria-expanded={wave.statsEnabled ? wave.statsOpen : undefined}
        aria-controls={wave.statsOpen ? `${counterKey}-wave-stats` : undefined}
        aria-busy={wave.pendingIncrements > 0 || undefined}
        onClick={() => void increment()}
        onContextMenu={(event) => {
          if (!wave.statsEnabled) return
          event.preventDefault()
          void open('pointer')
        }}
        onKeyDown={(event) => {
          if (event.key === 'Escape' && wave.statsOpen) {
            event.preventDefault()
            dismiss(true)
          } else if (event.key === 'ContextMenu' || (event.key === 'F10' && event.shiftKey)) {
            if (wave.statsEnabled) {
              event.preventDefault()
              void open('keyboard')
            }
          }
        }}
        onPointerDown={beginLongPress}
        onPointerMove={cancelMovedLongPress}
        onPointerUp={cancelLongPress}
        onPointerCancel={cancelLongPress}
      >
        <span className="wave-counter__icon" aria-hidden="true">
          {renderIcon?.() ?? (typeof icon === 'function' ? icon() : icon) ?? <CoffeeIcon />}
        </span>
        {children?.({ total: total ?? 0, pending: wave.pendingIncrements, unavailable }) ?? (
          <span data-testid="total" data-total="" className="wave-counter__total">{total ?? '—'}</span>
        )}
        {unavailable && <span className="wave-counter__sr-only" role="status">Counter unavailable</span>}
      </button>

      {showPopover && (
        <section
          ref={popover}
          id={`${counterKey}-wave-stats`}
          className={popoverClasses}
          style={popoverStyle}
          role="dialog"
          aria-label={title}
          tabIndex={-1}
          onKeyDown={(event) => {
            if (event.key === 'Escape') {
              event.preventDefault()
              dismiss(true)
            }
          }}
        >
          {renderAnalytics?.({
            analytics: wave.analytics,
            window: wave.analyticsWindow,
            loading: wave.analyticsLoading,
            error: wave.analyticsError,
            setWindow: selectAnalyticsWindow,
            retry,
          }) ?? (
            <>
              <div className="wave-counter__heading">
                <div>
                  <p className="wave-counter__eyebrow">Activity</p>
                  <h2>{capitalize(counterKey)}</h2>
                </div>
                <div className="wave-counter__heading-actions">
                  <div className="wave-counter__window-switch" aria-label="Activity range">
                    {ANALYTICS_WINDOWS.map((option) => (
                      <button
                        key={option.window}
                        type="button"
                        aria-label={option.label}
                        aria-pressed={wave.analyticsWindow === option.window}
                        onClick={() => void selectAnalyticsWindow(option.window)}
                      >
                        {option.label}
                      </button>
                    ))}
                  </div>
                  <button className="wave-counter__close" type="button" aria-label="Close statistics" onClick={() => dismiss(true)}>
                    <span aria-hidden="true">×</span>
                  </button>
                </div>
              </div>
              {wave.analyticsLoading ? (
                <div className="wave-counter__loading" role="status">Loading activity</div>
              ) : wave.analyticsError ? (
                <div className="wave-counter__error" role="alert">
                  <p>Activity is unavailable.</p>
                  <button type="button" onClick={() => void retry()}>Try again</button>
                </div>
              ) : wave.analytics ? (
                <div className="wave-counter__analytics">
                  <div className="wave-counter__summary-row"><strong>{wave.analytics.total}</strong><span>events</span></div>
                  <p data-testid="comparison" data-comparison="" className="wave-counter__comparison">{comparison}</p>
                  <AnalyticsChart analytics={wave.analytics} animate={animateChart} />
                  <p className="wave-counter__range">{dateRange}</p>
                  <p data-testid="accessible-summary" data-accessible-summary="" className="wave-counter__sr-only">{summary}</p>
                </div>
              ) : null}
            </>
          )}
        </section>
      )}
    </span>
  )
}

function asError(error: unknown): Error {
  return error instanceof Error ? error : new Error(String(error))
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1)
}

function describeTrigger(counterKey: string, total: number | undefined, statsEnabled: boolean): string {
  const totalDescription = total === undefined ? 'unavailable' : `${total} total`
  const statsDescription = statsEnabled ? ' Right click, long press, or use the context menu key for statistics.' : ''
  return `Add one ${counterKey}. ${totalDescription}.${statsDescription}`
}

function comparisonText(analytics: Analytics | null, window: AnalyticsWindow): string {
  if (!analytics) return ''
  if (window === 'all') {
    return analytics.total === 0 ? 'No all-time events' : `${analytics.total} all-time events`
  }
  const previousPeriod = window === '1M' ? 'previous 30 days' : 'previous seven days'
  if (analytics.previousTotal === 0) {
    return analytics.total === 0
      ? `No events in this or the ${previousPeriod}`
      : `${analytics.total} events, with none in the ${previousPeriod}`
  }
  const change = analytics.changePercentage ?? 0
  return `${Math.abs(change)}% ${change >= 0 ? 'more' : 'less'} than the ${previousPeriod}`
}

function rangeText(analytics: Analytics | null, window: AnalyticsWindow): string {
  if (!analytics?.points.length) return defaultRangeText(window)
  const formatter = new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', timeZone: 'UTC' })
  const first = analytics.points[0]
  const last = analytics.points.at(-1)
  return first && last
    ? `${formatter.format(new Date(first.start))} to ${formatter.format(new Date(last.start))}, UTC`
    : defaultRangeText(window)
}

function summaryText(analytics: Analytics | null, window: AnalyticsWindow): string {
  if (!analytics) return ''
  return `${analytics.total} events in ${windowSummary(window)}. Daily counts: ${analytics.points.map((point) => point.count).join(', ')}. ${comparisonText(analytics, window)}.`
}

function defaultRangeText(window: AnalyticsWindow): string {
  if (window === '1M') return 'Last 30 UTC days'
  if (window === 'all') return 'All-time UTC activity'
  return 'Last seven UTC days'
}

function windowSummary(window: AnalyticsWindow): string {
  if (window === '1M') return 'the last 30 days'
  if (window === 'all') return 'all time'
  return 'the last seven days'
}
